apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - name: management
          image: syswift/management
          env:
            - name: MONGO_URI
              value: 'mongodb://management-mongo-srv:27017/management'
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                      name: jwt-secret
                      key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: management-srv
spec:
  selector:
    app: management
  ports:
    - name: management
      protocol: TCP
      port: 5000
      targetPort: 5000